<a href="https://colab.research.google.com/github/paulalopez4/Entreglables_2/blob/master/LISTADO_DE_MEDICAMENTOS_EN_VENTA_LIBRE_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas

import pandas as pd

# 1. Series

medicamentos_venta_libre = pd.Series(
    ["Acetaminofén", "Ibuprofeno", "Loratadina", "Omeprazol", "Aspirina"],
    name="Medicamentos_Venta_Libre"
)

print(medicamentos_venta_libre)

0    Acetaminofén
1      Ibuprofeno
2      Loratadina
3       Omeprazol
4        Aspirina
Name: Medicamentos_Venta_Libre, dtype: object

In [ ]:
# 2. DataFrame desde diccionario

df = pd.DataFrame({
    "medicamento": ["Acetaminofén", "Ibuprofeno", "Loratadina", "Omeprazol", "Aspirina"],
    "categoría": ["Analgésico", "Antiinflamatorio", "Antihistamínico", "Antiácido", "Analgésico"],
    "presentación": ["Tabletas", "Tabletas", "Tabletas", "Cápsulas", "Tabletas"],
    "precio_aprox": [5000, 7000, 8000, 12000, 6000]  # precios en COP
})

print(df)

    medicamento         categoría presentación  precio_aprox
0  Acetaminofén        Analgésico     Tabletas          5000
1    Ibuprofeno  Antiinflamatorio     Tabletas          7000
2    Loratadina   Antihistamínico     Tabletas          8000
3     Omeprazol         Antiácido     Cápsulas         12000
4      Aspirina        Analgésico     Tabletas          6000

In [ ]:
# 2. leer dataFrames


# df = pd.read_json("datos.json")

url_drugs = "https://www.datos.gov.co/resource/xzwx-qpja.json"
df_drugs = pd.read_json(url_drugs)

df_drugs.head()

,principioactivo,concentracion,formafarmaceutica
0,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...,NO REPORTA,UNGÜENTO TÓPICO
1,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...,6 G + 4 5 G + 4 5 G +8 G / 100 G,UNGÜENTO TÓPICO
2,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...,6 G + 5 G + 3 G +4 8 G / 100 G,UNGÜENTO TÓPICO
3,ACEITE DE HÍGADO DE PESCADO + OXIDO DE ZINC,20 G + 27 G /100 G,CREMA TÓPICA
4,ACETAMINOFÉN,HASTA LA CONCENTRACIÓN DE 500 MG,TODAS LAS PRESENTACIONES POR VÍA ORAL

In [ ]:
# 3. como explorar un dataFrame

# cabeza del dataFrame
#df_drugs.head()

# cola del dataFrame
df_drugs.tail()

# info general
#df_drugs.info()

# estadistica descriptiva
#df_drugs.describe()

# slicing
#df_drugs.shape

# columnas
#df_drugs.columns

,principioactivo,concentracion,formafarmaceutica
955,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...,0 1 G / 100 G,CREMA TOPICA
956,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...,10 G / 100 G,CREMA TOPICA
957,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...,35 G / 100 G,CREMA TOPICA
958,YODOPOLIVINILPIRROLIDONA EQUIVALENTE A YODO LI...,10 MG + 1 G +1 G +12 G / 100 ML,SOLUCIÓN TÓPICA
959,YODURO DE TIBEZONIO,5 MG,TABLETA

In [ ]:
# 3. Seleccion de datos

#df_drugs["concentracion"]
df_drugs[["concentracion", "principioactivo"]]

,concentracion,principioactivo
0,NO REPORTA,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...
1,6 G + 4 5 G + 4 5 G +8 G / 100 G,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...
2,6 G + 5 G + 3 G +4 8 G / 100 G,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...
3,20 G + 27 G /100 G,ACEITE DE HÍGADO DE PESCADO + OXIDO DE ZINC
4,HASTA LA CONCENTRACIÓN DE 500 MG,ACETAMINOFÉN
...,...,...
955,0 1 G / 100 G,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...
956,10 G / 100 G,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...
957,35 G / 100 G,YODO POLIVINIL PIRROLIDONA+MENTOL LEVOROTATORI...
958,10 MG + 1 G +1 G +12 G / 100 ML,YODOPOLIVINILPIRROLIDONA EQUIVALENTE A YODO LI...
959,5 MG,YODURO DE TIBEZONIO

In [ ]:
# 4. Seleccion de datos (indexados)

df_drugs.iloc[800]

principioactivo       PIRANTEL EMBONATO
concentracion                    250 MG
formafarmaceutica    TABLETA MASTICABLE
Name: 800, dtype: object

In [ ]:
# 5. filtros

#seleccionar todos los medicamentos con un principio activo específico
df_drugs[df_drugs["principioactivo"] == "ACETAMINOFÉN"]

#buscar varios principios activos
#df_drugs[df_drugs["principioactivo"].isin(["ACETAMINOFÉN", "OMEPRAZOL", "LORATADINA"])]

,principioactivo,concentracion,formafarmaceutica
4,ACETAMINOFÉN,HASTA LA CONCENTRACIÓN DE 500 MG,TODAS LAS PRESENTACIONES POR VÍA ORAL
5,ACETAMINOFÉN,3 2G / 100ML,JARABE
6,ACETAMINOFÉN,5G / 100ML,JARABE
7,ACETAMINOFÉN,500MG,TABLETA
8,ACETAMINOFÉN,250MG,SUPOSITORIO
9,ACETAMINOFÉN,325MG,TABLETA
10,ACETAMINOFÉN,125MG,GRANULADO-SACHET
11,ACETAMINOFÉN,250MG,GRANULADO-SACHET
12,ACETAMINOFÉN,325MG,GRANULADO-SACHET

In [ ]:
# 6. operaciones de columnas

df_drugs["longitud_nombre"] = df_drugs["principioactivo"].str.len()

print(df_drugs["longitud_nombre"])

0      72
1      72
2      62
3      43
4      12
       ..
955    68
956    68
957    68
958    86
959    19
Name: longitud_nombre, Length: 960, dtype: int64

In [ ]:
# 7. manejo de valores faltantes

#df_drugs.isnull().sum()
df.dropna()
#df.fillna(0)
#df.fillna(df.mean())

    medicamento         categoría presentación  precio_aprox
0  Acetaminofén        Analgésico     Tabletas          5000
1    Ibuprofeno  Antiinflamatorio     Tabletas          7000
2    Loratadina   Antihistamínico     Tabletas          8000
3     Omeprazol         Antiácido     Cápsulas         12000
4      Aspirina        Analgésico     Tabletas          6000

In [ ]:
# 8. ordenar datos

df_drugs.sort_values("concentracion")

,principioactivo,concentracion,formafarmaceutica,longitud_nombre
549,FLUORURO SÓDICO,0 00098,SOLUCIÓN,15
598,HEXETIDINA,0 001,SOLUCIÓN BUCOFARÍNGEA,10
603,HIDROCORTISONA TÓPICO,0 001,POMADA,22
900,TRICLOSÁN,0 002 G / 100 ML,SOLUCIÓN TÓPICA,9
502,DICLOFENACO DIETILAMINA,0 01,AEROSOL,23
...,...,...,...,...
248,BACILLUS CLAUSII,ESPORAS DE BACILLUS CLAUSII 400 MILLONES/5ML,SUSPENSION ORAL,16
249,BACILLUS CLAUSII,ESPORAS DE BACILLUS CLAUSII 4000 MILLONES DE U...,NO REPORTA,16
4,ACETAMINOFÉN,HASTA LA CONCENTRACIÓN DE 500 MG,TODAS LAS PRESENTACIONES POR VÍA ORAL,12
718,NAPROXENO SÓDICO,MENOR O IGUAL A 250MG,TODAS,16
0,ACEITE ESENCIAL DE EUCALIPTO + MENTOL + ALCAN...,NO REPORTA,UNGÜENTO TÓPICO,72